"""Traditional Chinese is shipped as an available, AI-generated language (#403).

Locks the activation done for the chinese_traditional language addition:
  * the real ``languages/chinese_traditional/ui.json`` parses and is in the
    ``{ht, at}`` shape,
  * chinese_traditional ships AI-only: every leaf has an empty ``ht`` (no
    human translator yet) and a non-empty ``at`` -- so every key is flagged
    for a future human pass while nothing renders as raw English,
  * every ``{placeholder}`` in the English source survives into the
    chinese_traditional ``at`` (a dropped/renamed token would crash
    ``str.format`` at runtime), with the same ``{plural}`` drop on
    ``dialogs.suppressed_errors_suffix`` the source **chinese** (Simplified)
    translation already made,
  * the guided tour (``tutorial.*``) is translated,
  * chinese_traditional appears in the language selector (it is not a stub),
  * the SC language id maps to ``chinese_(traditional)`` so apply-to-game
    writes the Localization folder and ``g_language`` the game actually
    loads,
  * ``languages/sources.json`` carries a chinese_traditional base.ini URL,
  * the Config tab's language selector shows the coverage-caveat label
    instead of the generic title-cased folder name.

Unlike every other language here, chinese_traditional's ui.json was
generated by converting the existing **chinese** (Simplified) translation to
Traditional Chinese via OpenCC (Taiwan-standard, phrase-aware conversion),
not translated independently from English -- see TRANSLATIONS.md's 2.4.0
backfill-log entry for the method and the ambiguous-character verification
pass. These tests guard the same activation contract every other language
locks; they don't re-verify the conversion itself.

Mirrors test_german_activation.py / test_japanese_activation.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "src"))

from utils.settings import AppSettings, SC_LANGUAGE_IDS  # noqa: E402

pytestmark = [pytest.mark.unit, pytest.mark.regression]

_ZT_UI = REPO / "languages" / "chinese_traditional" / "ui.json"
_EN_UI = REPO / "languages" / "english" / "ui.json"
_PLACEHOLDER = re.compile(r"\{[^}]+\}")


def _leaves(node, prefix=""):
    """Yield (dotpath, leaf) for every translation leaf in the tree."""
    for k, v in node.items():
        if k == "_comment":
            continue
        p = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict) and ("ht" in v or "at" in v):
            yield p, v
        elif isinstance(v, dict):
            yield from _leaves(v, p)


def test_chinese_traditional_ui_json_is_valid_ht_at_shape():
    data = json.loads(_ZT_UI.read_text(encoding="utf-8"))
    leaves = list(_leaves(data))
    assert leaves, "chinese_traditional ui.json has no translation leaves"
    for path, leaf in leaves:
        assert set(leaf) >= {"ht", "at"}, f"{path} is not an {{ht, at}} leaf: {leaf!r}"
        assert isinstance(leaf["ht"], str) and isinstance(leaf["at"], str)


def test_chinese_traditional_is_ai_only_every_leaf_at_filled_ht_empty():
    data = json.loads(_ZT_UI.read_text(encoding="utf-8"))
    leaves = list(_leaves(data))
    # AI-only language: ht empty everywhere (needs-review marker), at non-empty
    # so nothing falls back to raw English in the UI.
    bad_ht = [p for p, leaf in leaves if leaf["ht"].strip()]
    empty_at = [p for p, leaf in leaves if not leaf["at"].strip()]
    assert not bad_ht, f"AI-only language should have empty ht: {bad_ht[:5]}"
    assert not empty_at, f"AI language should have every at filled: {empty_at[:5]}"
    assert len(leaves) > 300


def test_chinese_traditional_covers_full_english_key_universe():
    en = {p for p, _ in _leaves(json.loads(_EN_UI.read_text(encoding="utf-8")))}
    zt = {p for p, _ in _leaves(json.loads(_ZT_UI.read_text(encoding="utf-8")))}
    missing = sorted(en - zt)
    assert not missing, f"chinese_traditional is missing keys English already has: {missing[:10]}"
    # No extras either (outside tutorial.*, which is language-only by design --
    # English carries no tutorial section). A stray extra key usually means
    # ui.json was translated against a newer/different English snapshot than
    # this branch's actual key set.
    extra = sorted(p for p in (zt - en) if not p.startswith("tutorial."))
    assert not extra, (
        f"chinese_traditional has keys English on this branch doesn't have: {extra[:10]}"
    )


# dialogs.suppressed_errors_suffix's {plural} is deliberately dropped, matching
# the source chinese (Simplified) translation this file was converted from --
# Chinese doesn't pluralize by suffix, so a generic {plural} token has no
# correct value to hold. German, Spanish, and Portuguese make the same call
# for this key (str.format ignores unused kwargs, so a dropped placeholder in
# the string is harmless) -- see TRANSLATIONS.md's backfill-log precedent.
_ALLOWED_PLACEHOLDER_DROPS = {
    "dialogs.suppressed_errors_suffix": {"{plural}"},
}


def test_chinese_traditional_placeholders_match_english_source():
    en = {p: leaf for p, leaf in _leaves(json.loads(_EN_UI.read_text(encoding="utf-8")))}
    zt = {p: leaf for p, leaf in _leaves(json.loads(_ZT_UI.read_text(encoding="utf-8")))}
    mismatches = []
    for path, en_leaf in en.items():
        if path not in zt:
            continue
        en_tokens = set(_PLACEHOLDER.findall(en_leaf.get("ht", "")))
        zt_tokens = set(_PLACEHOLDER.findall(zt[path].get("at", "")))
        allowed_drop = _ALLOWED_PLACEHOLDER_DROPS.get(path, set())
        if en_tokens - zt_tokens != allowed_drop or zt_tokens - en_tokens:
            mismatches.append((path, sorted(en_tokens), sorted(zt_tokens)))
    assert not mismatches, f"placeholder drift: {mismatches[:5]}"


def test_chinese_traditional_translates_the_guided_tour():
    data = json.loads(_ZT_UI.read_text(encoding="utf-8"))
    tour = data.get("tutorial", {})
    assert len(tour) >= 19, "chinese_traditional guided tour is missing steps"
    for step_id, step in tour.items():
        assert step["title"]["at"].strip(), f"tutorial.{step_id}.title not translated"
        assert step["description"]["at"].strip(), f"tutorial.{step_id}.description not translated"


def test_chinese_traditional_is_available_in_selector():
    assert "chinese_traditional" in AppSettings.get_available_languages()


def test_chinese_traditional_maps_to_traditional_localization_id():
    assert SC_LANGUAGE_IDS["chinese_traditional"] == "chinese_(traditional)"
    assert AppSettings.get_sc_language_id("chinese_traditional") == "chinese_(traditional)"


def test_sources_json_has_chinese_traditional_url():
    sources = json.loads((REPO / "languages" / "sources.json").read_text(encoding="utf-8"))
    assert sources.get("chinese_traditional", "").startswith("https://")


def test_chinese_traditional_docs_exist():
    lang_dir = REPO / "languages" / "chinese_traditional"
    for filename in ("HELP.md", "ABOUT.md", "LEGAL.md", "FAQ.md"):
        assert (lang_dir / filename).exists(), (
            f"languages/chinese_traditional/{filename} is missing"
        )


def test_selector_shows_the_coverage_caveat_label():
    """#403: the source is a snapshot (67.3% key coverage, stopped updating
    May 2024) -- the language selector must say so up front rather than let
    picking it be a silent surprise."""
    from gui.config_tab import _LANGUAGE_COMBO_LABEL_OVERRIDES

    assert _LANGUAGE_COMBO_LABEL_OVERRIDES["chinese_traditional"] == "Traditional Chinese (67.3%)"
